# Google Cloud Build 配置文件
# 用于自动构建和部署到 Cloud Run

steps:
  # 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kaskade-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kaskade-backend:latest'
      - '.'

  # 推送镜像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/kaskade-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/kaskade-backend:latest'

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kaskade-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kaskade-backend:$SHORT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/kaskade-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/kaskade-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY

